version: "3.8"

services:
  userdb:
    image: mysql
    container_name: db-user
    restart: on-failure
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: admin
      DEVICE_PORT: 8081
      DEVICE_HOST: device-management
    networks:
      - ems-network

  user-app:
    hostname: user-management
    restart: on-failure
    depends_on:
      - userdb
    image: user-management-app
    container_name: user-management-container
    build: .
    ports:
      - "8000:8080"
    environment:
      - DB_IP=userdb
      - DEVICE_PORT=8081
      - DEVICE_HOST=device-management
    networks:
      - ems-network

networks:
  ems-network:
    external: true